# Generated by Django 6.0.2 on 2026-02-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=255)),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('updated_at',
                 models.DateTimeField(
                     auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='board',
                to='kanban_app.project'),
        ),
    ]
